//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintHelper {
    
    
    #region Component Designer generated code 
    public partial class IPrintHelper_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::PrintHelper.@__IPrintHelper.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::PrintHelper.IPrintHelper), typeof(global::PrintHelper.IPrintHelper_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::PrintHelper.IPrintHelper), typeof(global::PrintHelper.IPrintHelper_))]
    internal sealed partial class @__IPrintHelper : global::java.lang.Object, global::PrintHelper.IPrintHelper {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetPrinters0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_GetPrinterStatus1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_PrintPDF2;
        
        private @__IPrintHelper(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::PrintHelper.@__IPrintHelper.staticClass = @__class;
            global::PrintHelper.@__IPrintHelper.j4n_GetPrinters0 = @__env.GetMethodID(global::PrintHelper.@__IPrintHelper.staticClass, "GetPrinters", "()[Ljava/lang/String;");
            global::PrintHelper.@__IPrintHelper.j4n_GetPrinterStatus1 = @__env.GetMethodID(global::PrintHelper.@__IPrintHelper.staticClass, "GetPrinterStatus", "(Ljava/lang/String;)Ljava/lang/String;");
            global::PrintHelper.@__IPrintHelper.j4n_PrintPDF2 = @__env.GetMethodID(global::PrintHelper.@__IPrintHelper.staticClass, "PrintPDF", "(Ljava/lang/String;Ljava/lang/String;IIII)Lsystem/Object;");
        }
        
        public string[] GetPrinters() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::PrintHelper.@__IPrintHelper.j4n_GetPrinters0));
            }
        }
        
        public string GetPrinterStatus(string Printer) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::PrintHelper.@__IPrintHelper.j4n_GetPrinterStatus1, global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, Printer)));
            }
        }
        
        public object PrintPDF(string Printer, string FileName, int printRange, int pageFrom, int pageTo, int copies) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 22)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, @__env.CallObjectMethodPtr(this, global::PrintHelper.@__IPrintHelper.j4n_PrintPDF2, global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, Printer), global::net.sf.jni4net.utils.Convertor.ParStrongC2JString(@__env, FileName), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(printRange), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(pageFrom), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(pageTo), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(copies)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__IPrintHelper);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetPrinters", "GetPrinters0", "()[Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetPrinterStatus", "GetPrinterStatus1", "(Ljava/lang/String;)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "PrintPDF", "PrintPDF2", "(Ljava/lang/String;Ljava/lang/String;IIII)Lsystem/Object;"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetPrinters0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Ljava/lang/String;
            // ()[LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PrintHelper.IPrintHelper @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::PrintHelper.IPrintHelper>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayStrongC2JString(@__env, @__real.GetPrinters());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetPrinterStatus1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle Printer) {
            // (Ljava/lang/String;)Ljava/lang/String;
            // (LSystem/String;)LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PrintHelper.IPrintHelper @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::PrintHelper.IPrintHelper>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.GetPrinterStatus(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, Printer)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle PrintPDF2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle Printer, global::net.sf.jni4net.utils.JniLocalHandle FileName, int printRange, int pageFrom, int pageTo, int copies) {
            // (Ljava/lang/String;Ljava/lang/String;IIII)Lsystem/Object;
            // (LSystem/String;LSystem/String;IIII)LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::PrintHelper.IPrintHelper @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::PrintHelper.IPrintHelper>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, @__real.PrintPDF(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, Printer), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, FileName), printRange, pageFrom, pageTo, copies));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::PrintHelper.@__IPrintHelper(@__env);
            }
        }
    }
    #endregion
}
