// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package printhelper;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IPrintHelper_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return printhelper.IPrintHelper_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        printhelper.IPrintHelper_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IPrintHelper extends system.Object implements printhelper.IPrintHelper {
    
    protected __IPrintHelper(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()[LSystem/String;")
    public native java.lang.String[] GetPrinters();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native java.lang.String GetPrinterStatus(java.lang.String Printer);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;IIII)LSystem/Object;")
    public native system.Object PrintPDF(java.lang.String Printer, java.lang.String FileName, int printRange, int pageFrom, int pageTo, int copies);
}
//</generated-proxy>
