// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package printhelper;

@net.sf.jni4net.attributes.ClrType
public class ReturnMessage extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ReturnMessage(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ReturnMessage() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        printhelper.ReturnMessage.__ctorReturnMessage0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorReturnMessage0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean getSuccess();
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)V")
    public native void setSuccess(boolean value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getMessage();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setMessage(java.lang.String value);
    
    public static system.Type typeof() {
        return printhelper.ReturnMessage.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        printhelper.ReturnMessage.staticType = staticType;
    }
    //</generated-proxy>
}
