// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package printhelper;

@net.sf.jni4net.attributes.ClrType
public class PrintHelper extends system.Object implements printhelper.IPrintHelper {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected PrintHelper(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public PrintHelper() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        printhelper.PrintHelper.__ctorPrintHelper0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorPrintHelper0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String HelloWorld();
    
    @net.sf.jni4net.attributes.ClrMethod("()[LSystem/String;")
    public native java.lang.String[] GetPrinters();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/String;")
    public native java.lang.String GetPrinterStatus(java.lang.String Printer);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;IIII)LSystem/String;")
    public native java.lang.String PrintPDF(java.lang.String Printer, java.lang.String FileName, int printRange, int pageFrom, int pageTo, int copies);
    
    public static system.Type typeof() {
        return printhelper.PrintHelper.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        printhelper.PrintHelper.staticType = staticType;
    }
    //</generated-proxy>
}
